# Generated by Django 6.0.2 on 2026-02-10 07:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Ad')),
                ('name_en', models.CharField(max_length=255, null=True, verbose_name='Ad')),
                ('name_tr', models.CharField(max_length=255, null=True, verbose_name='Ad')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Slug (url uç kısmı)')),
                ('collection', models.CharField(choices=[('stand', 'Standlar'), ('part', 'Parçalar')], max_length=10, verbose_name='Koleksiyon')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('description_tr', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('rich_text', models.TextField(blank=True, verbose_name='Zengin metin')),
                ('rich_text_en', models.TextField(blank=True, null=True, verbose_name='Zengin metin')),
                ('rich_text_tr', models.TextField(blank=True, null=True, verbose_name='Zengin metin')),
                ('seo_canonical', models.URLField(blank=True, default='', editable=False, verbose_name='Kanonik URL')),
                ('publish_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Yayım tarihi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme tarihi')),
            ],
            options={
                'verbose_name': 'Kategori',
                'verbose_name_plural': 'Kategoriler',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CategoryDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Başlık')),
                ('file', models.FileField(upload_to='categories/documents/', verbose_name='Dosya')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Sıralama')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='products.category', verbose_name='Kategori')),
            ],
            options={
                'verbose_name': 'Kategori dokümanı',
                'verbose_name_plural': 'Kategori dokümanları',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CategoryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='categories/images/', verbose_name='Görsel')),
                ('alt_text', models.CharField(blank=True, max_length=255, verbose_name='Alternatif metin')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Birincil')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Sıralama')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.category', verbose_name='Kategori')),
            ],
            options={
                'verbose_name': 'Kategori görseli',
                'verbose_name_plural': 'Kategori görselleri',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Ad')),
                ('name_en', models.CharField(max_length=255, null=True, verbose_name='Ad')),
                ('name_tr', models.CharField(max_length=255, null=True, verbose_name='Ad')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True, verbose_name='Slug')),
                ('min_size', models.CharField(blank=True, max_length=100, verbose_name='Minimum ölçü')),
                ('max_size', models.CharField(blank=True, max_length=100, verbose_name='Maksimum ölçü')),
                ('color', models.CharField(blank=True, max_length=100, verbose_name='Renk')),
                ('color_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='Renk')),
                ('color_tr', models.CharField(blank=True, max_length=100, null=True, verbose_name='Renk')),
                ('publish_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Yayım tarihi')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('description_tr', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('rich_text', models.TextField(blank=True, verbose_name='Zengin metin')),
                ('rich_text_en', models.TextField(blank=True, null=True, verbose_name='Zengin metin')),
                ('rich_text_tr', models.TextField(blank=True, null=True, verbose_name='Zengin metin')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme tarihi')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.category', verbose_name='Kategori')),
            ],
            options={
                'verbose_name': 'Ürün',
                'verbose_name_plural': 'Ürünler',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Başlık')),
                ('file', models.FileField(upload_to='products/documents/', verbose_name='Dosya')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Sıralama')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='products.product', verbose_name='Ürün')),
            ],
            options={
                'verbose_name': 'Ürün dokümanı',
                'verbose_name_plural': 'Ürün dokümanları',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/images/', verbose_name='Görsel')),
                ('alt_text', models.CharField(blank=True, max_length=255, verbose_name='Alternatif metin')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Birincil')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Sıralama')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product', verbose_name='Ürün')),
            ],
            options={
                'verbose_name': 'Ürün görseli',
                'verbose_name_plural': 'Ürün görselleri',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True, verbose_name='Kod (SKU)')),
                ('size', models.CharField(blank=True, max_length=100, verbose_name='Ölçü')),
                ('size_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ölçü')),
                ('size_tr', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ölçü')),
                ('package_weight', models.CharField(blank=True, max_length=100, verbose_name='Paket ağırlığı')),
                ('package_size', models.CharField(blank=True, max_length=100, verbose_name='Paket ölçüsü')),
                ('package_quantity', models.CharField(blank=True, max_length=100, verbose_name='Paket içi adet')),
                ('minimum_order', models.CharField(blank=True, max_length=100, verbose_name='Minimum sipariş')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.product', verbose_name='Ürün')),
            ],
            options={
                'verbose_name': 'Ürün Varyantı',
                'verbose_name_plural': 'Ürün Varyantları',
                'ordering': ['code'],
            },
        ),
    ]
