# Generated by Django 6.0.2 on 2026-02-04 13:14

import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('name_en', models.CharField(max_length=255, null=True, verbose_name='Name')),
                ('name_tr', models.CharField(max_length=255, null=True, verbose_name='Name')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('description_tr', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('rich_text', models.TextField(blank=True, verbose_name='Rich text')),
                ('rich_text_en', models.TextField(blank=True, null=True, verbose_name='Rich text')),
                ('rich_text_tr', models.TextField(blank=True, null=True, verbose_name='Rich text')),
                ('seo_title', models.CharField(blank=True, max_length=255, verbose_name='SEO title')),
                ('seo_title_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='SEO title')),
                ('seo_title_tr', models.CharField(blank=True, max_length=255, null=True, verbose_name='SEO title')),
                ('seo_description', models.CharField(blank=True, max_length=500, verbose_name='SEO description')),
                ('seo_description_en', models.CharField(blank=True, max_length=500, null=True, verbose_name='SEO description')),
                ('seo_description_tr', models.CharField(blank=True, max_length=500, null=True, verbose_name='SEO description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='products.category', verbose_name='Parent')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CategoryDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Title')),
                ('file', models.FileField(upload_to='categories/documents/', verbose_name='File')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Sort order')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='products.category', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Category document',
                'verbose_name_plural': 'Category documents',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CategoryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='categories/images/', verbose_name='Image')),
                ('alt_text', models.CharField(blank=True, max_length=255, verbose_name='Alt text')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Is primary')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Sort order')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.category', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Category image',
                'verbose_name_plural': 'Category images',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('name_en', models.CharField(max_length=255, null=True, verbose_name='Name')),
                ('name_tr', models.CharField(max_length=255, null=True, verbose_name='Name')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Slug')),
                ('code', models.CharField(max_length=100, verbose_name='Code')),
                ('size', models.CharField(blank=True, max_length=100, verbose_name='Size')),
                ('min_size', models.CharField(blank=True, max_length=100, verbose_name='Min size')),
                ('max_size', models.CharField(blank=True, max_length=100, verbose_name='Max size')),
                ('color', models.CharField(blank=True, max_length=100, verbose_name='Color')),
                ('weight', models.CharField(blank=True, max_length=100, verbose_name='Ağırlık')),
                ('package_size', models.CharField(blank=True, max_length=100, verbose_name='Paket ölçüsü')),
                ('package_quantity', models.CharField(blank=True, max_length=100, verbose_name='Paket içi adet')),
                ('minimum_order', models.CharField(blank=True, max_length=100, verbose_name='Minimum sipariş')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('description_tr', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('rich_text', models.TextField(blank=True, verbose_name='Rich text')),
                ('rich_text_en', models.TextField(blank=True, null=True, verbose_name='Rich text')),
                ('rich_text_tr', models.TextField(blank=True, null=True, verbose_name='Rich text')),
                ('seo_title', models.CharField(blank=True, max_length=255, verbose_name='SEO title')),
                ('seo_title_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='SEO title')),
                ('seo_title_tr', models.CharField(blank=True, max_length=255, null=True, verbose_name='SEO title')),
                ('seo_description', models.CharField(blank=True, max_length=500, verbose_name='SEO description')),
                ('seo_description_en', models.CharField(blank=True, max_length=500, null=True, verbose_name='SEO description')),
                ('seo_description_tr', models.CharField(blank=True, max_length=500, null=True, verbose_name='SEO description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.category', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Title')),
                ('file', models.FileField(upload_to='products/documents/', verbose_name='File')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Sort order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='products.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Product document',
                'verbose_name_plural': 'Product documents',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/images/', verbose_name='Image')),
                ('alt_text', models.CharField(blank=True, max_length=255, verbose_name='Alt text')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Is primary')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Sort order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Product image',
                'verbose_name_plural': 'Product images',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
