# Generated by Django 6.0.2 on 2026-02-06 09:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Varsayılan dilde kategori adı. 'Ad (en)' alanını da mutlaka doldurun.", max_length=255, verbose_name='Ad')),
                ('name_en', models.CharField(help_text="Varsayılan dilde kategori adı. 'Ad (en)' alanını da mutlaka doldurun.", max_length=255, null=True, verbose_name='Ad')),
                ('name_tr', models.CharField(help_text="Varsayılan dilde kategori adı. 'Ad (en)' alanını da mutlaka doldurun.", max_length=255, null=True, verbose_name='Ad')),
                ('slug', models.SlugField(blank=True, help_text="URL dostu ad; boş bırakırsanız İngilizce addan türetilir (ör. 'Apple laptops' → 'apple-laptops').", max_length=255, unique=True, verbose_name='Kısa ad')),
                ('description', models.TextField(blank=True, help_text="Liste sayfalarında görünen kısa özet. Örnek: 'Tüm Dizüstü Bilgisayar modelleri tek yerde'.", verbose_name='Açıklama')),
                ('description_en', models.TextField(blank=True, help_text="Liste sayfalarında görünen kısa özet. Örnek: 'Tüm Dizüstü Bilgisayar modelleri tek yerde'.", null=True, verbose_name='Açıklama')),
                ('description_tr', models.TextField(blank=True, help_text="Liste sayfalarında görünen kısa özet. Örnek: 'Tüm Dizüstü Bilgisayar modelleri tek yerde'.", null=True, verbose_name='Açıklama')),
                ('rich_text', models.TextField(blank=True, help_text='Kategori sayfasındaki uzun içerik; Dizüstü bilgisayar satın alma rehberi gibi metinleri ekleyin.', verbose_name='Zengin metin')),
                ('rich_text_en', models.TextField(blank=True, help_text='Kategori sayfasındaki uzun içerik; Dizüstü bilgisayar satın alma rehberi gibi metinleri ekleyin.', null=True, verbose_name='Zengin metin')),
                ('rich_text_tr', models.TextField(blank=True, help_text='Kategori sayfasındaki uzun içerik; Dizüstü bilgisayar satın alma rehberi gibi metinleri ekleyin.', null=True, verbose_name='Zengin metin')),
                ('seo_title', models.CharField(blank=True, help_text="Tarayıcı sekmesinde görünür. Örnek: 'Dizüstü Bilgisayar Modelleri | ATA Dizayn'.", max_length=255, verbose_name='SEO başlığı')),
                ('seo_title_en', models.CharField(blank=True, help_text="Tarayıcı sekmesinde görünür. Örnek: 'Dizüstü Bilgisayar Modelleri | ATA Dizayn'.", max_length=255, null=True, verbose_name='SEO başlığı')),
                ('seo_title_tr', models.CharField(blank=True, help_text="Tarayıcı sekmesinde görünür. Örnek: 'Dizüstü Bilgisayar Modelleri | ATA Dizayn'.", max_length=255, null=True, verbose_name='SEO başlığı')),
                ('seo_description', models.CharField(blank=True, help_text="Arama sonuçlarında çıkan açıklama. Örnek: 'Dizüstü bilgisayar seçerken performans ve pil ömrü önerileri'.", max_length=500, verbose_name='SEO açıklaması')),
                ('seo_description_en', models.CharField(blank=True, help_text="Arama sonuçlarında çıkan açıklama. Örnek: 'Dizüstü bilgisayar seçerken performans ve pil ömrü önerileri'.", max_length=500, null=True, verbose_name='SEO açıklaması')),
                ('seo_description_tr', models.CharField(blank=True, help_text="Arama sonuçlarında çıkan açıklama. Örnek: 'Dizüstü bilgisayar seçerken performans ve pil ömrü önerileri'.", max_length=500, null=True, verbose_name='SEO açıklaması')),
                ('seo_heading_primary', models.CharField(blank=True, help_text="Sayfa içinde `<h1>` olarak kullanılır. Örnek: 'Dizüstü Bilgisayar Modelleri'.", max_length=255, verbose_name='H1 başlığı')),
                ('seo_heading_primary_en', models.CharField(blank=True, help_text="Sayfa içinde `<h1>` olarak kullanılır. Örnek: 'Dizüstü Bilgisayar Modelleri'.", max_length=255, null=True, verbose_name='H1 başlığı')),
                ('seo_heading_primary_tr', models.CharField(blank=True, help_text="Sayfa içinde `<h1>` olarak kullanılır. Örnek: 'Dizüstü Bilgisayar Modelleri'.", max_length=255, null=True, verbose_name='H1 başlığı')),
                ('seo_heading_secondary', models.CharField(blank=True, help_text="`<h2>` seviyesinde görünen başlık. Örnek: 'Intel Core i7 Dizüstü Bilgisayar Seçenekleri'.", max_length=255, verbose_name='H2 başlığı')),
                ('seo_heading_secondary_en', models.CharField(blank=True, help_text="`<h2>` seviyesinde görünen başlık. Örnek: 'Intel Core i7 Dizüstü Bilgisayar Seçenekleri'.", max_length=255, null=True, verbose_name='H2 başlığı')),
                ('seo_heading_secondary_tr', models.CharField(blank=True, help_text="`<h2>` seviyesinde görünen başlık. Örnek: 'Intel Core i7 Dizüstü Bilgisayar Seçenekleri'.", max_length=255, null=True, verbose_name='H2 başlığı')),
                ('seo_heading_tertiary', models.CharField(blank=True, help_text="`<h3>` veya alt bölüm için kullanılacak başlık. Örnek: 'Pil Ömrü Tavsiyeleri'.", max_length=255, verbose_name='H3 başlığı')),
                ('seo_heading_tertiary_en', models.CharField(blank=True, help_text="`<h3>` veya alt bölüm için kullanılacak başlık. Örnek: 'Pil Ömrü Tavsiyeleri'.", max_length=255, null=True, verbose_name='H3 başlığı')),
                ('seo_heading_tertiary_tr', models.CharField(blank=True, help_text="`<h3>` veya alt bölüm için kullanılacak başlık. Örnek: 'Pil Ömrü Tavsiyeleri'.", max_length=255, null=True, verbose_name='H3 başlığı')),
                ('seo_canonical', models.URLField(blank=True, default='', editable=False, help_text='Sistem otomatik oluşturur; manuel giriş gerekmez.', verbose_name='Kanonik URL')),
                ('publish_date', models.DateField(default=django.utils.timezone.localdate, help_text='Kategori yayına alınma tarihi; bugün tarihi otomatik gelir.', verbose_name='Yayım tarihi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme tarihi')),
            ],
            options={
                'verbose_name': 'Kategori',
                'verbose_name_plural': 'Kategoriler',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CategoryDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text="Belge başlığı. Örnek: 'Dizüstü Bilgisayar Teknik Kılavuzu'.", max_length=255, verbose_name='Başlık')),
                ('file', models.FileField(help_text='PDF, katalog vb. Örnek: Dizüstü bilgisayar PDF kataloğu.', upload_to='categories/documents/', verbose_name='Dosya')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Belge sırası; 0 dizüstü bilgisayar kataloğunu en üstte tutar.', verbose_name='Sıralama')),
                ('category', models.ForeignKey(help_text='Örnek: Dizüstü bilgisayar kategori kataloğu.', on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='products.category', verbose_name='Kategori')),
            ],
            options={
                'verbose_name': 'Kategori dokümanı',
                'verbose_name_plural': 'Kategori dokümanları',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CategoryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Kategoriye ait görseli yükleyin; örn. Dizüstü bilgisayar ürün fotoğrafı.', upload_to='categories/images/', verbose_name='Görsel')),
                ('alt_text', models.CharField(blank=True, help_text="Erişilebilirlik metni. Örnek: 'Dizüstü bilgisayar ön görünüm'.", max_length=255, verbose_name='Alternatif metin')),
                ('is_primary', models.BooleanField(default=False, help_text='Ana görsel olarak kullanılsın mı? Dizüstü bilgisayar vitrini için işaretleyin.', verbose_name='Birincil')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Düşük sayılar ilk gösterilir. Dizüstü bilgisayar kapak görseli için 0 girin.', verbose_name='Sıralama')),
                ('category', models.ForeignKey(help_text='Örnek: Dizüstü Bilgisayar görsel grubu.', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.category', verbose_name='Kategori')),
            ],
            options={
                'verbose_name': 'Kategori görseli',
                'verbose_name_plural': 'Kategori görselleri',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Varsayılan dilde ürün adı. 'Ad (en)' alanını da mutlaka doldurun.", max_length=255, verbose_name='Ad')),
                ('name_en', models.CharField(help_text="Varsayılan dilde ürün adı. 'Ad (en)' alanını da mutlaka doldurun.", max_length=255, null=True, verbose_name='Ad')),
                ('name_tr', models.CharField(help_text="Varsayılan dilde ürün adı. 'Ad (en)' alanını da mutlaka doldurun.", max_length=255, null=True, verbose_name='Ad')),
                ('code', models.SlugField(help_text="URL/stok kodu; boş bırakırsanız İngilizce addan türetilir (ör. 'Apple Laptop Pro' → 'apple-laptop-pro').", max_length=100, unique=True, verbose_name='Kod')),
                ('size', models.CharField(blank=True, help_text='Ölçü bilgisi. Örnek: 15,6 inç ekran.', max_length=100, verbose_name='Ölçü')),
                ('min_size', models.CharField(blank=True, help_text='Serideki en küçük değer. Örnek: 13 inç Dizüstü bilgisayar.', max_length=100, verbose_name='Minimum ölçü')),
                ('max_size', models.CharField(blank=True, help_text='Serideki en büyük değer. Örnek: 18 inç Dizüstü bilgisayar.', max_length=100, verbose_name='Maksimum ölçü')),
                ('color', models.CharField(blank=True, help_text="Renk varyasyonu. Örnek: 'Uzay Grisi dizüstü bilgisayar'.", max_length=100, verbose_name='Renk')),
                ('weight', models.CharField(blank=True, help_text='Nakliye için ağırlık. Örnek: 1,30 kg Dizüstü bilgisayar.', max_length=100, verbose_name='Ağırlık')),
                ('package_size', models.CharField(blank=True, help_text='Kutunun ölçüleri. Örnek: 45×30×10 cm Dizüstü bilgisayar kutusu.', max_length=100, verbose_name='Paket ölçüsü')),
                ('package_quantity', models.CharField(blank=True, help_text='Bir kolideki adet. Örnek: 5 Dizüstü bilgisayar / koli.', max_length=100, verbose_name='Paket içi adet')),
                ('minimum_order', models.CharField(blank=True, help_text='Minimum sipariş miktarı. Örnek: 10 adet Dizüstü bilgisayar.', max_length=100, verbose_name='Minimum sipariş')),
                ('publish_date', models.DateField(default=django.utils.timezone.localdate, help_text='Ürünün yayına girdiği tarih; bugün tarihi otomatik gelir.', verbose_name='Yayım tarihi')),
                ('description', models.TextField(blank=True, help_text="Kısa ürün özeti. Örnek: 'Magnesium kasalı hafif dizüstü bilgisayar'.", verbose_name='Açıklama')),
                ('description_en', models.TextField(blank=True, help_text="Kısa ürün özeti. Örnek: 'Magnesium kasalı hafif dizüstü bilgisayar'.", null=True, verbose_name='Açıklama')),
                ('description_tr', models.TextField(blank=True, help_text="Kısa ürün özeti. Örnek: 'Magnesium kasalı hafif dizüstü bilgisayar'.", null=True, verbose_name='Açıklama')),
                ('rich_text', models.TextField(blank=True, help_text="Teknik detayların yer aldığı uzun metin. Örnek: 'Intel Core i7, 16 GB RAM, 1 TB SSD'.", verbose_name='Zengin metin')),
                ('rich_text_en', models.TextField(blank=True, help_text="Teknik detayların yer aldığı uzun metin. Örnek: 'Intel Core i7, 16 GB RAM, 1 TB SSD'.", null=True, verbose_name='Zengin metin')),
                ('rich_text_tr', models.TextField(blank=True, help_text="Teknik detayların yer aldığı uzun metin. Örnek: 'Intel Core i7, 16 GB RAM, 1 TB SSD'.", null=True, verbose_name='Zengin metin')),
                ('seo_title', models.CharField(blank=True, help_text="Arama sonuçlarındaki başlık. Örnek: 'Dizüstü Bilgisayar Pro 15 - Intel Core i7'.", max_length=255, verbose_name='SEO başlığı')),
                ('seo_title_en', models.CharField(blank=True, help_text="Arama sonuçlarındaki başlık. Örnek: 'Dizüstü Bilgisayar Pro 15 - Intel Core i7'.", max_length=255, null=True, verbose_name='SEO başlığı')),
                ('seo_title_tr', models.CharField(blank=True, help_text="Arama sonuçlarındaki başlık. Örnek: 'Dizüstü Bilgisayar Pro 15 - Intel Core i7'.", max_length=255, null=True, verbose_name='SEO başlığı')),
                ('seo_description', models.CharField(blank=True, help_text="Arama sonuçlarında görünen açıklama. Örnek: 'Dizüstü Bilgisayar Pro 15, 16 GB RAM ve 1 TB SSD ile gelir'.", max_length=500, verbose_name='SEO açıklaması')),
                ('seo_description_en', models.CharField(blank=True, help_text="Arama sonuçlarında görünen açıklama. Örnek: 'Dizüstü Bilgisayar Pro 15, 16 GB RAM ve 1 TB SSD ile gelir'.", max_length=500, null=True, verbose_name='SEO açıklaması')),
                ('seo_description_tr', models.CharField(blank=True, help_text="Arama sonuçlarında görünen açıklama. Örnek: 'Dizüstü Bilgisayar Pro 15, 16 GB RAM ve 1 TB SSD ile gelir'.", max_length=500, null=True, verbose_name='SEO açıklaması')),
                ('seo_heading_primary', models.CharField(blank=True, help_text="Ürün detay sayfasındaki `<h1>` metni. Örnek: 'Dizüstü Bilgisayar Pro 15'.", max_length=255, verbose_name='H1 başlığı')),
                ('seo_heading_primary_en', models.CharField(blank=True, help_text="Ürün detay sayfasındaki `<h1>` metni. Örnek: 'Dizüstü Bilgisayar Pro 15'.", max_length=255, null=True, verbose_name='H1 başlığı')),
                ('seo_heading_primary_tr', models.CharField(blank=True, help_text="Ürün detay sayfasındaki `<h1>` metni. Örnek: 'Dizüstü Bilgisayar Pro 15'.", max_length=255, null=True, verbose_name='H1 başlığı')),
                ('seo_heading_secondary', models.CharField(blank=True, help_text="Detay sayfasındaki `<h2>` alanı. Örnek: 'Performans ve Soğutma Sistemi'.", max_length=255, verbose_name='H2 başlığı')),
                ('seo_heading_secondary_en', models.CharField(blank=True, help_text="Detay sayfasındaki `<h2>` alanı. Örnek: 'Performans ve Soğutma Sistemi'.", max_length=255, null=True, verbose_name='H2 başlığı')),
                ('seo_heading_secondary_tr', models.CharField(blank=True, help_text="Detay sayfasındaki `<h2>` alanı. Örnek: 'Performans ve Soğutma Sistemi'.", max_length=255, null=True, verbose_name='H2 başlığı')),
                ('seo_heading_tertiary', models.CharField(blank=True, help_text="Alt blokta kullanılacak `<h3>`. Örnek: 'Bağlantı Seçenekleri ve Portlar'.", max_length=255, verbose_name='H3 başlığı')),
                ('seo_heading_tertiary_en', models.CharField(blank=True, help_text="Alt blokta kullanılacak `<h3>`. Örnek: 'Bağlantı Seçenekleri ve Portlar'.", max_length=255, null=True, verbose_name='H3 başlığı')),
                ('seo_heading_tertiary_tr', models.CharField(blank=True, help_text="Alt blokta kullanılacak `<h3>`. Örnek: 'Bağlantı Seçenekleri ve Portlar'.", max_length=255, null=True, verbose_name='H3 başlığı')),
                ('seo_canonical', models.URLField(blank=True, default='', editable=False, help_text='Sistem otomatik oluşturur; manuel giriş gerekmez.', verbose_name='Kanonik URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme tarihi')),
                ('category', models.ForeignKey(help_text='Ürünün bağlı olduğu kategori. Örnek: Dizüstü Bilgisayarlar.', on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.category', verbose_name='Kategori')),
            ],
            options={
                'verbose_name': 'Ürün',
                'verbose_name_plural': 'Ürünler',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text="Belge adı. Örnek: 'Dizüstü Bilgisayar Pro 15 PDF'.", max_length=255, verbose_name='Başlık')),
                ('file', models.FileField(help_text='Teknik föy, kullanım kılavuzu vb.', upload_to='products/documents/', verbose_name='Dosya')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Belge gösterim sırası.', verbose_name='Sıralama')),
                ('product', models.ForeignKey(help_text='Örnek: Dizüstü Bilgisayar Pro 15 kullanım kılavuzu.', on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='products.product', verbose_name='Ürün')),
            ],
            options={
                'verbose_name': 'Ürün dokümanı',
                'verbose_name_plural': 'Ürün dokümanları',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Ürün görselini yükleyin; örn. Dizüstü bilgisayar açık ekran.', upload_to='products/images/', verbose_name='Görsel')),
                ('alt_text', models.CharField(blank=True, help_text="Örnek: 'Dizüstü Bilgisayar Pro 15 üstten görünüm'.", max_length=255, verbose_name='Alternatif metin')),
                ('is_primary', models.BooleanField(default=False, help_text='Ürün kartlarında kullanılacak ana görseli işaretleyin.', verbose_name='Birincil')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Galeri sırası; 0 değerini Dizüstü bilgisayar kapak fotoğrafı için kullanın.', verbose_name='Sıralama')),
                ('product', models.ForeignKey(help_text='Örnek: Dizüstü Bilgisayar Pro 15 için galeri.', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product', verbose_name='Ürün')),
            ],
            options={
                'verbose_name': 'Ürün görseli',
                'verbose_name_plural': 'Ürün görselleri',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
