# Generated by Django 6.0.2 on 2026-02-16 11:16

import django.utils.timezone
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='seo_canonical',
        ),
        migrations.AlterField(
            model_name='category',
            name='collection',
            field=models.CharField(blank=True, choices=[('stand', 'Standlar'), ('part', 'Parçalar')], max_length=10, null=True, verbose_name='Koleksiyon'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Açıklama'),
        ),
        migrations.AlterField(
            model_name='category',
            name='publish_date',
            field=models.DateField(blank=True, default=django.utils.timezone.localdate, null=True, verbose_name='Yayım tarihi'),
        ),
        migrations.AlterField(
            model_name='category',
            name='rich_text',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Zengin metin'),
        ),
        migrations.AlterField(
            model_name='categorydocument',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='categories/documents/', verbose_name='Dosya'),
        ),
        migrations.AlterField(
            model_name='categorydocument',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Başlık'),
        ),
        migrations.AlterField(
            model_name='categoryimage',
            name='alt_text',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Alternatif metin'),
        ),
        migrations.AlterField(
            model_name='categoryimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='categories/images/', verbose_name='Görsel'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Açıklama'),
        ),
        migrations.AlterField(
            model_name='product',
            name='publish_date',
            field=models.DateField(blank=True, default=django.utils.timezone.localdate, null=True, verbose_name='Yayım tarihi'),
        ),
        migrations.AlterField(
            model_name='product',
            name='rich_text',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Zengin metin'),
        ),
        migrations.AlterField(
            model_name='productdocument',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='products/documents/', verbose_name='Dosya'),
        ),
        migrations.AlterField(
            model_name='productdocument',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Başlık'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='alt_text',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Alternatif metin'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/images/', verbose_name='Görsel'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='minimum_order',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Minimum sipariş'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='package_quantity',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Paket içi adet'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='package_size',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Paket ölçüsü'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='package_weight',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Paket ağırlığı'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='size',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ölçü'),
        ),
    ]
