# Generated by Django 6.0.2 on 2026-02-12 19:24

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=autoslug.fields.AutoSlugField(blank=True, editable=True, help_text='Lütfen gerekmedikçe değiştirmeyin.', max_length=255, populate_from='name', unique=True, verbose_name='Slug (url uç kısmı)'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug_en',
            field=autoslug.fields.AutoSlugField(blank=True, editable=True, help_text='Lütfen gerekmedikçe değiştirmeyin.', max_length=255, null=True, populate_from='name', unique=True, verbose_name='Slug (url uç kısmı)'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug_tr',
            field=autoslug.fields.AutoSlugField(blank=True, editable=True, help_text='Lütfen gerekmedikçe değiştirmeyin.', max_length=255, null=True, populate_from='name', unique=True, verbose_name='Slug (url uç kısmı)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=autoslug.fields.AutoSlugField(blank=True, editable=True, help_text='Lütfen gerekmedikçe değiştirmeyin.', max_length=100, populate_from='name', unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug_en',
            field=autoslug.fields.AutoSlugField(blank=True, editable=True, help_text='Lütfen gerekmedikçe değiştirmeyin.', max_length=100, null=True, populate_from='name', unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug_tr',
            field=autoslug.fields.AutoSlugField(blank=True, editable=True, help_text='Lütfen gerekmedikçe değiştirmeyin.', max_length=100, null=True, populate_from='name', unique=True, verbose_name='Slug'),
        ),
    ]
