# Generated by Django 6.0.2 on 2026-02-10 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='color',
        ),
        migrations.RemoveField(
            model_name='product',
            name='color_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='color_tr',
        ),
        migrations.RemoveField(
            model_name='product',
            name='max_size',
        ),
        migrations.RemoveField(
            model_name='product',
            name='min_size',
        ),
    ]
