# Generated by Django 6.0.2 on 2026-02-06 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='seo_description',
        ),
        migrations.RemoveField(
            model_name='category',
            name='seo_description_en',
        ),
        migrations.RemoveField(
            model_name='category',
            name='seo_description_tr',
        ),
        migrations.RemoveField(
            model_name='category',
            name='seo_heading_primary',
        ),
        migrations.RemoveField(
            model_name='category',
            name='seo_heading_primary_en',
        ),
        migrations.RemoveField(
            model_name='category',
            name='seo_heading_primary_tr',
        ),
        migrations.RemoveField(
            model_name='category',
            name='seo_heading_secondary',
        ),
        migrations.RemoveField(
            model_name='category',
            name='seo_heading_secondary_en',
        ),
        migrations.RemoveField(
            model_name='category',
            name='seo_heading_secondary_tr',
        ),
        migrations.RemoveField(
            model_name='category',
            name='seo_heading_tertiary',
        ),
        migrations.RemoveField(
            model_name='category',
            name='seo_heading_tertiary_en',
        ),
        migrations.RemoveField(
            model_name='category',
            name='seo_heading_tertiary_tr',
        ),
        migrations.RemoveField(
            model_name='category',
            name='seo_title',
        ),
        migrations.RemoveField(
            model_name='category',
            name='seo_title_en',
        ),
        migrations.RemoveField(
            model_name='category',
            name='seo_title_tr',
        ),
        migrations.RemoveField(
            model_name='product',
            name='seo_canonical',
        ),
        migrations.RemoveField(
            model_name='product',
            name='seo_description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='seo_description_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='seo_description_tr',
        ),
        migrations.RemoveField(
            model_name='product',
            name='seo_heading_primary',
        ),
        migrations.RemoveField(
            model_name='product',
            name='seo_heading_primary_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='seo_heading_primary_tr',
        ),
        migrations.RemoveField(
            model_name='product',
            name='seo_heading_secondary',
        ),
        migrations.RemoveField(
            model_name='product',
            name='seo_heading_secondary_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='seo_heading_secondary_tr',
        ),
        migrations.RemoveField(
            model_name='product',
            name='seo_heading_tertiary',
        ),
        migrations.RemoveField(
            model_name='product',
            name='seo_heading_tertiary_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='seo_heading_tertiary_tr',
        ),
        migrations.RemoveField(
            model_name='product',
            name='seo_title',
        ),
        migrations.RemoveField(
            model_name='product',
            name='seo_title_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='seo_title_tr',
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Ad'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Ad'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_tr',
            field=models.CharField(max_length=255, null=True, verbose_name='Ad'),
        ),
        migrations.AlterField(
            model_name='category',
            name='seo_canonical',
            field=models.URLField(blank=True, default='', editable=False, verbose_name='Kanonik URL'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Kısa ad'),
        ),
    ]
