# Generated by Django 6.0.2 on 2026-02-04 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.SlugField(max_length=100, unique=True, verbose_name='Code'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('parent', 'slug'), name='unique_category_slug_per_parent'),
        ),
    ]
