# Generated by Django 6.0.2 on 2026-02-11 07:04

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_product_color_remove_product_color_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='rich_text',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Zengin metin'),
        ),
        migrations.AlterField(
            model_name='category',
            name='rich_text_en',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Zengin metin'),
        ),
        migrations.AlterField(
            model_name='category',
            name='rich_text_tr',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Zengin metin'),
        ),
        migrations.AlterField(
            model_name='product',
            name='rich_text',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Zengin metin'),
        ),
        migrations.AlterField(
            model_name='product',
            name='rich_text_en',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Zengin metin'),
        ),
        migrations.AlterField(
            model_name='product',
            name='rich_text_tr',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Zengin metin'),
        ),
    ]
