# Generated by Django 6.0.2 on 2026-02-06 10:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_category_seo_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='collection',
            field=models.CharField(choices=[('stand', 'Standlar'), ('part', 'Parçalar')], default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='color_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Renk'),
        ),
        migrations.AddField(
            model_name='product',
            name='color_tr',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Renk'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, verbose_name='Açıklama'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Açıklama'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description_tr',
            field=models.TextField(blank=True, null=True, verbose_name='Açıklama'),
        ),
        migrations.AlterField(
            model_name='category',
            name='publish_date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='Yayım tarihi'),
        ),
        migrations.AlterField(
            model_name='category',
            name='rich_text',
            field=models.TextField(blank=True, verbose_name='Zengin metin'),
        ),
        migrations.AlterField(
            model_name='category',
            name='rich_text_en',
            field=models.TextField(blank=True, null=True, verbose_name='Zengin metin'),
        ),
        migrations.AlterField(
            model_name='category',
            name='rich_text_tr',
            field=models.TextField(blank=True, null=True, verbose_name='Zengin metin'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.category', verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.SlugField(max_length=100, unique=True, verbose_name='Kod'),
        ),
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, max_length=100, verbose_name='Renk'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, verbose_name='Açıklama'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Açıklama'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_tr',
            field=models.TextField(blank=True, null=True, verbose_name='Açıklama'),
        ),
        migrations.AlterField(
            model_name='product',
            name='max_size',
            field=models.CharField(blank=True, max_length=100, verbose_name='Maksimum ölçü'),
        ),
        migrations.AlterField(
            model_name='product',
            name='min_size',
            field=models.CharField(blank=True, max_length=100, verbose_name='Minimum ölçü'),
        ),
        migrations.AlterField(
            model_name='product',
            name='minimum_order',
            field=models.CharField(blank=True, max_length=100, verbose_name='Minimum sipariş'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Ad'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Ad'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_tr',
            field=models.CharField(max_length=255, null=True, verbose_name='Ad'),
        ),
        migrations.AlterField(
            model_name='product',
            name='package_quantity',
            field=models.CharField(blank=True, max_length=100, verbose_name='Paket içi adet'),
        ),
        migrations.AlterField(
            model_name='product',
            name='package_size',
            field=models.CharField(blank=True, max_length=100, verbose_name='Paket ölçüsü'),
        ),
        migrations.AlterField(
            model_name='product',
            name='publish_date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='Yayım tarihi'),
        ),
        migrations.AlterField(
            model_name='product',
            name='rich_text',
            field=models.TextField(blank=True, verbose_name='Zengin metin'),
        ),
        migrations.AlterField(
            model_name='product',
            name='rich_text_en',
            field=models.TextField(blank=True, null=True, verbose_name='Zengin metin'),
        ),
        migrations.AlterField(
            model_name='product',
            name='rich_text_tr',
            field=models.TextField(blank=True, null=True, verbose_name='Zengin metin'),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ölçü'),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ağırlık'),
        ),
    ]
