# Generated by Django 6.0.2 on 2026-02-06 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_slug_alter_product_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='collection',
            field=models.CharField(choices=[('stand', 'Standlar'), ('part', 'Parçalar')], max_length=10, verbose_name='Koleksiyon'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Slug (url uç kısmı)'),
        ),
    ]
