# Generated by Django 6.0.2 on 2026-02-06 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_category_collection_alter_category_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='weight',
        ),
        migrations.AddField(
            model_name='product',
            name='package_weight',
            field=models.CharField(blank=True, max_length=100, verbose_name='Paket ağırlığı'),
        ),
    ]
