# Generated by Django 6.0.2 on 2026-02-10 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BrandCarouselImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_name', models.CharField(help_text="Bootstrap icon name (e.g., 'bi-microsoft')", max_length=100)),
                ('alt_text', models.CharField(help_text='Alternative text for accessibility', max_length=255)),
                ('alt_text_en', models.CharField(help_text='Alternative text for accessibility', max_length=255, null=True)),
                ('alt_text_tr', models.CharField(help_text='Alternative text for accessibility', max_length=255, null=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order in carousel')),
                ('is_active', models.BooleanField(default=True, help_text='Show/hide this brand in carousel')),
            ],
            options={
                'verbose_name': 'Brand Carousel Image',
                'verbose_name_plural': 'Brand Carousel Images',
                'ordering': ['order'],
            },
        ),
    ]
