# Generated by Django 6.0.2 on 2026-02-12 08:52

import django.utils.timezone
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BrandCarouselImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(help_text='Brand logo image (PNG, JPG, SVG, etc.)', upload_to='brands/carousel/')),
                ('alt_text', models.CharField(help_text='Alternative text for accessibility', max_length=255)),
                ('website_url', models.URLField(blank=True, help_text="Customer's website URL (optional)", null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Show/hide this brand in carousel')),
            ],
            options={
                'verbose_name': 'Brand Carousel Image',
                'verbose_name_plural': 'Brand Carousel Images',
            },
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Policy name (e.g., 'Gizlilik Politikası')", max_length=255)),
                ('name_en', models.CharField(help_text="Policy name (e.g., 'Gizlilik Politikası')", max_length=255, null=True)),
                ('name_tr', models.CharField(help_text="Policy name (e.g., 'Gizlilik Politikası')", max_length=255, null=True)),
                ('slug', models.SlugField(help_text="URL friendly name (e.g., 'gizlilik-politikasi')", max_length=255, unique=True)),
                ('content', django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='The full text of the policy')),
                ('content_en', django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='The full text of the policy', null=True)),
                ('content_tr', django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='The full text of the policy', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Show/hide this policy in the footer')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of appearance in the footer')),
                ('updated_at', models.DateField(default=django.utils.timezone.localdate, help_text='Last modified date (editable, defaults to today)')),
            ],
            options={
                'verbose_name': 'Policy',
                'verbose_name_plural': 'Policies',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SiteAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(help_text="Unique key to reference this asset in templates (e.g., 'hero_video', 'footer_logo')", max_length=100, unique=True)),
                ('file', models.FileField(help_text='Upload the asset file (Image, Video, PDF, etc.)', upload_to='assets/')),
                ('description', models.CharField(blank=True, help_text='Internal note about where this asset is used', max_length=255)),
            ],
            options={
                'verbose_name': 'Site Asset',
                'verbose_name_plural': 'Site Assets',
            },
        ),
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text="Unique key for configuration (e.g., 'contact_email')", max_length=100, unique=True)),
                ('value', models.TextField(help_text='Configuration value')),
                ('value_en', models.TextField(help_text='Configuration value', null=True)),
                ('value_tr', models.TextField(help_text='Configuration value', null=True)),
                ('description', models.CharField(blank=True, help_text='Internal note about what this setting does', max_length=255)),
            ],
            options={
                'verbose_name': 'Site Configuration',
                'verbose_name_plural': 'Site Configurations',
            },
        ),
    ]
