# Generated by Django 6.0.2 on 2026-02-10 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brandcarouselimage',
            name='alt_text_en',
        ),
        migrations.RemoveField(
            model_name='brandcarouselimage',
            name='alt_text_tr',
        ),
        migrations.AlterField(
            model_name='brandcarouselimage',
            name='alt_text',
            field=models.CharField(help_text='Alternative text for accessibility (not translated)', max_length=255),
        ),
    ]
