# Generated by Django 6.0.2 on 2026-02-12 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='policy',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Politika', 'verbose_name_plural': 'Politikalar'},
        ),
        migrations.AlterModelOptions(
            name='siteconfiguration',
            options={'verbose_name': 'Site konfigürasyonu', 'verbose_name_plural': 'Site konfigürasyonları'},
        ),
    ]
