# Generated by Django 6.0.2 on 2026-02-16 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brandcarouselimage',
            options={'verbose_name': 'Marka Şerit Görseli', 'verbose_name_plural': 'Marka Şerit Görselleri'},
        ),
        migrations.AlterModelOptions(
            name='siteasset',
            options={'verbose_name': 'Site Varlığı', 'verbose_name_plural': 'Site Varlıkları'},
        ),
        migrations.AlterField(
            model_name='brandcarouselimage',
            name='alt_text',
            field=models.CharField(help_text='Erişilebilirlik için alternatif metin', max_length=255),
        ),
        migrations.AlterField(
            model_name='brandcarouselimage',
            name='image',
            field=models.FileField(help_text='Marka logo görseli (PNG, JPG, SVG vb.)', upload_to='brands/carousel/'),
        ),
        migrations.AlterField(
            model_name='brandcarouselimage',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Bu markayı kaydırıcıda göster/gizle'),
        ),
        migrations.AlterField(
            model_name='brandcarouselimage',
            name='website_url',
            field=models.URLField(blank=True, default='', help_text="Müşteri web sitesi URL'si (isteğe bağlı)"),
        ),
        migrations.AlterField(
            model_name='siteasset',
            name='description',
            field=models.CharField(blank=True, help_text='Bu varlığın nerede kullanıldığına dair dahili not', max_length=255),
        ),
        migrations.AlterField(
            model_name='siteasset',
            name='file',
            field=models.FileField(help_text='Varlık dosyasını yükleyin (Resim, Video, PDF vb.)', upload_to='assets/'),
        ),
        migrations.AlterField(
            model_name='siteasset',
            name='key',
            field=models.SlugField(help_text="Şablonlarda bu varlığa referans vermek için benzersiz anahtar (örn. 'hero_video', 'footer_logo')", max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='description',
            field=models.CharField(blank=True, help_text='Bu ayarın ne yaptığını anlatan dahili not', max_length=255),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='key',
            field=models.CharField(help_text="Konfigürasyon için benzersiz anahtar (örn. 'contact_email')", max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='value',
            field=models.TextField(help_text='Konfigürasyon değeri'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='value_en',
            field=models.TextField(help_text='Konfigürasyon değeri', null=True),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='value_tr',
            field=models.TextField(help_text='Konfigürasyon değeri', null=True),
        ),
    ]
