# Generated by Django 6.0.2 on 2026-02-16 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_brandcarouselimage_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandcarouselimage',
            name='image',
            field=models.FileField(blank=True, help_text='Marka logo görseli (PNG, JPG, SVG vb.)', null=True, upload_to='brands/carousel/'),
        ),
        migrations.AlterField(
            model_name='brandcarouselimage',
            name='website_url',
            field=models.URLField(blank=True, default='', help_text="Müşteri web sitesi URL'si (isteğe bağlı)", null=True),
        ),
        migrations.AlterField(
            model_name='siteasset',
            name='description',
            field=models.CharField(blank=True, help_text='Bu varlığın nerede kullanıldığına dair dahili not', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='siteasset',
            name='file',
            field=models.FileField(blank=True, help_text='Varlık dosyasını yükleyin (Resim, Video, PDF vb.)', null=True, upload_to='assets/'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='description',
            field=models.CharField(blank=True, help_text='Bu ayarın ne yaptığını anlatan dahili not', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='value',
            field=models.TextField(blank=True, help_text='Konfigürasyon değeri', null=True),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='value_en',
            field=models.TextField(blank=True, help_text='Konfigürasyon değeri', null=True),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='value_tr',
            field=models.TextField(blank=True, help_text='Konfigürasyon değeri', null=True),
        ),
    ]
