# Generated by Django 6.0.2 on 2026-02-10 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_brandcarouselimage_alt_text_en_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brandcarouselimage',
            options={'verbose_name': 'Brand Carousel Image', 'verbose_name_plural': 'Brand Carousel Images'},
        ),
        migrations.RemoveField(
            model_name='brandcarouselimage',
            name='icon_name',
        ),
        migrations.RemoveField(
            model_name='brandcarouselimage',
            name='order',
        ),
        migrations.AddField(
            model_name='brandcarouselimage',
            name='image',
            field=models.ImageField(default='', help_text='Brand logo image', upload_to='brands/carousel/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='brandcarouselimage',
            name='alt_text',
            field=models.CharField(help_text='Alternative text for accessibility', max_length=255),
        ),
    ]
