# Generated by Django 6.0.2 on 2026-05-14 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_brandcarouselimage_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandcarouselimage',
            name='website_url',
            field=models.URLField(blank=True, default='', help_text="Müşteri web sitesi URL'si (isteğe bağlı)"),
        ),
        migrations.AlterField(
            model_name='siteasset',
            name='description',
            field=models.CharField(blank=True, default='', help_text='Bu varlığın nerede kullanıldığına dair dahili not', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='description',
            field=models.CharField(blank=True, default='', help_text='Bu ayarın ne yaptığını anlatan dahili not', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='value',
            field=models.TextField(blank=True, default='', help_text='Konfigürasyon değeri'),
            preserve_default=False,
        ),
    ]
