# Generated by Django 6.0.2 on 2026-02-10 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_brandcarouselimage_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandcarouselimage',
            name='image',
            field=models.FileField(help_text='Brand logo image (PNG, JPG, SVG, etc.)', upload_to='brands/carousel/'),
        ),
    ]
