# Generated by Django 6.0.2 on 2026-02-10 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_brandcarouselimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandcarouselimage',
            name='website_url',
            field=models.URLField(blank=True, help_text="Customer's website URL (optional)", null=True),
        ),
    ]
