# Generated by Django 6.0.2 on 2026-02-10 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_brandcarouselimage_website_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(help_text="Unique key to reference this asset in templates (e.g., 'hero_video', 'footer_logo')", max_length=100, unique=True)),
                ('file', models.FileField(help_text='Upload the asset file (Image, Video, PDF, etc.)', upload_to='assets/')),
                ('description', models.CharField(blank=True, help_text='Internal note about where this asset is used', max_length=255)),
            ],
            options={
                'verbose_name': 'Site Asset',
                'verbose_name_plural': 'Site Assets',
            },
        ),
    ]
