# Generated by Django 6.0.2 on 2026-02-12 19:05

import autoslug.fields
import django.utils.timezone
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Sayfanın H1 başlığı ve tarayıcı sekmesinde görünen isim.', max_length=255, verbose_name='Sayfa Başlığı')),
                ('title_en', models.CharField(help_text='Sayfanın H1 başlığı ve tarayıcı sekmesinde görünen isim.', max_length=255, null=True, verbose_name='Sayfa Başlığı')),
                ('title_tr', models.CharField(help_text='Sayfanın H1 başlığı ve tarayıcı sekmesinde görünen isim.', max_length=255, null=True, verbose_name='Sayfa Başlığı')),
                ('slug', autoslug.fields.AutoSlugField(blank=True, editable=False, help_text='Lütfen gerek görülmediği sürece değiştirmeyiniz! SEO performansını düşürür!', max_length=255, populate_from='title', unique=True, verbose_name='Slug')),
                ('slug_en', autoslug.fields.AutoSlugField(blank=True, editable=False, help_text='Lütfen gerek görülmediği sürece değiştirmeyiniz! SEO performansını düşürür!', max_length=255, null=True, populate_from='title', unique=True, verbose_name='Slug')),
                ('slug_tr', autoslug.fields.AutoSlugField(blank=True, editable=False, help_text='Lütfen gerek görülmediği sürece değiştirmeyiniz! SEO performansını düşürür!', max_length=255, null=True, populate_from='title', unique=True, verbose_name='Slug')),
                ('meta_description', models.TextField(help_text='Girilmediyse içerikten çekilir, daha güçlü SEO için giriniz ancak zorunlu değildir.', max_length=160, verbose_name='Meta / Kısa Açıklama')),
                ('meta_description_en', models.TextField(help_text='Girilmediyse içerikten çekilir, daha güçlü SEO için giriniz ancak zorunlu değildir.', max_length=160, null=True, verbose_name='Meta / Kısa Açıklama')),
                ('meta_description_tr', models.TextField(help_text='Girilmediyse içerikten çekilir, daha güçlü SEO için giriniz ancak zorunlu değildir.', max_length=160, null=True, verbose_name='Meta / Kısa Açıklama')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Sayfa İçeriği')),
                ('content_en', django_ckeditor_5.fields.CKEditor5Field(null=True, verbose_name='Sayfa İçeriği')),
                ('content_tr', django_ckeditor_5.fields.CKEditor5Field(null=True, verbose_name='Sayfa İçeriği')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='blog/covers/', verbose_name='Kapak Görseli')),
                ('cover_image_alt', models.CharField(blank=True, max_length=255, verbose_name='Kapak Görseli Alt Metni')),
                ('cover_image_alt_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Kapak Görseli Alt Metni')),
                ('cover_image_alt_tr', models.CharField(blank=True, max_length=255, null=True, verbose_name='Kapak Görseli Alt Metni')),
                ('status', models.CharField(choices=[('draft', 'Taslak'), ('published', 'Yayında')], default='draft', max_length=10, verbose_name='Durum')),
                ('publish_date', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Yayım Tarihi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
            ],
            options={
                'verbose_name': 'Blog Yazısı',
                'verbose_name_plural': 'Blog Yazıları',
                'ordering': ['-publish_date'],
            },
        ),
    ]
