# Generated by Django 6.0.2 on 2026-02-12 13:21

import django.utils.timezone
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Başlık')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Başlık')),
                ('title_tr', models.CharField(max_length=255, null=True, verbose_name='Başlık')),
                ('slug', models.SlugField(blank=True, editable=False, max_length=255, unique=True, verbose_name='Slug')),
                ('slug_en', models.SlugField(blank=True, editable=False, max_length=255, null=True, unique=True, verbose_name='Slug')),
                ('slug_tr', models.SlugField(blank=True, editable=False, max_length=255, null=True, unique=True, verbose_name='Slug')),
                ('excerpt', models.TextField(blank=True, help_text='Blog listesinde görünecek kısa metin.', max_length=500, verbose_name='Özet / Kısa Açıklama')),
                ('excerpt_en', models.TextField(blank=True, help_text='Blog listesinde görünecek kısa metin.', max_length=500, null=True, verbose_name='Özet / Kısa Açıklama')),
                ('excerpt_tr', models.TextField(blank=True, help_text='Blog listesinde görünecek kısa metin.', max_length=500, null=True, verbose_name='Özet / Kısa Açıklama')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(verbose_name='İçerik')),
                ('content_en', django_ckeditor_5.fields.CKEditor5Field(null=True, verbose_name='İçerik')),
                ('content_tr', django_ckeditor_5.fields.CKEditor5Field(null=True, verbose_name='İçerik')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='blog/covers/', verbose_name='Kapak Görseli')),
                ('cover_image_alt', models.CharField(blank=True, max_length=255, verbose_name='Kapak Görseli Alt Metni')),
                ('cover_image_alt_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Kapak Görseli Alt Metni')),
                ('cover_image_alt_tr', models.CharField(blank=True, max_length=255, null=True, verbose_name='Kapak Görseli Alt Metni')),
                ('meta_title', models.CharField(blank=True, help_text='Google sonuçlarında görünecek başlık. Boş bırakılırsa normal başlık kullanılır.', max_length=70, verbose_name='SEO Başlığı')),
                ('meta_title_en', models.CharField(blank=True, help_text='Google sonuçlarında görünecek başlık. Boş bırakılırsa normal başlık kullanılır.', max_length=70, null=True, verbose_name='SEO Başlığı')),
                ('meta_title_tr', models.CharField(blank=True, help_text='Google sonuçlarında görünecek başlık. Boş bırakılırsa normal başlık kullanılır.', max_length=70, null=True, verbose_name='SEO Başlığı')),
                ('meta_description', models.TextField(blank=True, help_text='Google sonuçlarında görünecek açıklama.', max_length=160, verbose_name='SEO Açıklaması')),
                ('meta_description_en', models.TextField(blank=True, help_text='Google sonuçlarında görünecek açıklama.', max_length=160, null=True, verbose_name='SEO Açıklaması')),
                ('meta_description_tr', models.TextField(blank=True, help_text='Google sonuçlarında görünecek açıklama.', max_length=160, null=True, verbose_name='SEO Açıklaması')),
                ('status', models.CharField(choices=[('draft', 'Taslak'), ('published', 'Yayında')], default='draft', max_length=10, verbose_name='Durum')),
                ('publish_date', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Yayım Tarihi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
            ],
            options={
                'verbose_name': 'Blog Yazısı',
                'verbose_name_plural': 'Blog Yazıları',
                'ordering': ['-publish_date'],
            },
        ),
    ]
