# Generated by Django 6.0.2 on 2026-02-12 13:31

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='excerpt',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='excerpt_en',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='excerpt_tr',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='meta_title',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='meta_title_en',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='meta_title_tr',
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Sayfa İçeriği'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='content_en',
            field=django_ckeditor_5.fields.CKEditor5Field(null=True, verbose_name='Sayfa İçeriği'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='content_tr',
            field=django_ckeditor_5.fields.CKEditor5Field(null=True, verbose_name='Sayfa İçeriği'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='meta_description',
            field=models.TextField(help_text='Google arama sonuçlarında ve blog listesinde görünecek özet (Max 160 karakter).', max_length=160, verbose_name='Meta / Kısa Açıklama'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='meta_description_en',
            field=models.TextField(help_text='Google arama sonuçlarında ve blog listesinde görünecek özet (Max 160 karakter).', max_length=160, null=True, verbose_name='Meta / Kısa Açıklama'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='meta_description_tr',
            field=models.TextField(help_text='Google arama sonuçlarında ve blog listesinde görünecek özet (Max 160 karakter).', max_length=160, null=True, verbose_name='Meta / Kısa Açıklama'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='title',
            field=models.CharField(help_text='Sayfanın H1 başlığı ve tarayıcı sekmesinde görünen isim.', max_length=255, verbose_name='Sayfa Başlığı'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='title_en',
            field=models.CharField(help_text='Sayfanın H1 başlığı ve tarayıcı sekmesinde görünen isim.', max_length=255, null=True, verbose_name='Sayfa Başlığı'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='title_tr',
            field=models.CharField(help_text='Sayfanın H1 başlığı ve tarayıcı sekmesinde görünen isim.', max_length=255, null=True, verbose_name='Sayfa Başlığı'),
        ),
    ]
