# Generated by Django 6.0.2 on 2026-02-16 11:16

import django.utils.timezone
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='collection',
            field=models.CharField(blank=True, choices=[('policy', 'Politikalar'), ('announcement', 'Duyurular'), ('post', 'Blog paylaşımları'), ('corporate', 'Kurumsal')], default='post', max_length=20, null=True, verbose_name='Koleksiyon'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Sayfa İçeriği'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='cover_image_alt',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Kapak Görseli Alt Metni'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='meta_description',
            field=models.TextField(blank=True, help_text='Girilmediyse içerikten çekilir, daha güçlü SEO için giriniz ancak zorunlu değildir.', max_length=160, null=True, verbose_name='Meta / Kısa Açıklama'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='publish_date',
            field=models.DateTimeField(blank=True, db_index=True, default=django.utils.timezone.now, null=True, verbose_name='Yayım Tarihi'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='status',
            field=models.CharField(blank=True, choices=[('draft', 'Taslak'), ('published', 'Yayında')], default='draft', max_length=10, null=True, verbose_name='Durum'),
        ),
    ]
