# Generated by Django 6.0.2 on 2026-02-12 19:24

import autoslug.fields
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Sayfa İçeriği'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='content_en',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Sayfa İçeriği'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='content_tr',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Sayfa İçeriği'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='meta_description',
            field=models.TextField(blank=True, help_text='Girilmediyse içerikten çekilir, daha güçlü SEO için giriniz ancak zorunlu değildir.', max_length=160, verbose_name='Meta / Kısa Açıklama'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='meta_description_en',
            field=models.TextField(blank=True, help_text='Girilmediyse içerikten çekilir, daha güçlü SEO için giriniz ancak zorunlu değildir.', max_length=160, null=True, verbose_name='Meta / Kısa Açıklama'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='meta_description_tr',
            field=models.TextField(blank=True, help_text='Girilmediyse içerikten çekilir, daha güçlü SEO için giriniz ancak zorunlu değildir.', max_length=160, null=True, verbose_name='Meta / Kısa Açıklama'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='slug',
            field=autoslug.fields.AutoSlugField(blank=True, editable=True, help_text='Lütfen gerekmedikçe değiştirmeyin.', max_length=255, populate_from='title', unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='slug_en',
            field=autoslug.fields.AutoSlugField(blank=True, editable=True, help_text='Lütfen gerekmedikçe değiştirmeyin.', max_length=255, null=True, populate_from='title', unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='slug_tr',
            field=autoslug.fields.AutoSlugField(blank=True, editable=True, help_text='Lütfen gerekmedikçe değiştirmeyin.', max_length=255, null=True, populate_from='title', unique=True, verbose_name='Slug'),
        ),
    ]
